# Generated by Django 5.0.6 on 2024-06-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="views",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
